table by_specialty

	column Specialty
		dataType: string
		summarizeBy: none
		sourceColumn: Specialty

	column target_days
		dataType: int64
		summarizeBy: sum
		sourceColumn: target_days

	column appointments
		dataType: int64
		summarizeBy: sum
		sourceColumn: appointments

	column avg_lead
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_lead

	column within_std_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: within_std_pct

	column no_show_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: no_show_pct

	measure 'Avg lead time (days) (by_specialty)' = AVERAGE ( 'by_specialty'[avg_lead] )
		formatString: #,0.00
		displayFolder: Measures
		/// Avg lead time (days) for the 'Lead time against each specialty's own access standard' visual.

	measure 'Target lead time (days) (by_specialty)' = SUM ( 'by_specialty'[target_days] )
		formatString: #,0.00
		displayFolder: Measures
		/// Target lead time (days) for the 'Lead time against each specialty's own access standard' visual.

	measure 'Within standard % (by_specialty)' = AVERAGE ( 'by_specialty'[within_std_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// Within standard % for the 'Compliance with access standard, by specialty' visual.

	partition by_specialty = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\by_specialty.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Specialty", type text},
				        {"target_days", Int64.Type},
				        {"appointments", Int64.Type},
				        {"avg_lead", type number},
				        {"within_std_pct", type number},
				        {"no_show_pct", type number}
				    })
				in
				    Typed
