table lead_bands

	column band
		dataType: string
		summarizeBy: none
		sourceColumn: band

	column appointments
		dataType: int64
		summarizeBy: sum
		sourceColumn: appointments

	column no_show_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: no_show_pct

	column cancel_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: cancel_pct

	measure 'No-show rate % (lead_bands)' = AVERAGE ( 'lead_bands'[no_show_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// No-show rate % for the 'Longer waits, worse attendance' visual.

	measure 'Cancellation rate % (lead_bands)' = AVERAGE ( 'lead_bands'[cancel_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// Cancellation rate % for the 'Longer waits, worse attendance' visual.

	partition lead_bands = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\lead_bands.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"band", type text},
				        {"appointments", Int64.Type},
				        {"no_show_pct", type number},
				        {"cancel_pct", type number}
				    })
				in
				    Typed
