table status

	column Status
		dataType: string
		summarizeBy: none
		sourceColumn: Status

	column appointments
		dataType: int64
		summarizeBy: sum
		sourceColumn: appointments

	measure 'Appointments (status)' = SUM ( 'status'[appointments] )
		formatString: #,0.00
		displayFolder: Measures
		/// Appointments for the 'Appointment outcomes' visual.

	partition status = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\status.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Status", type text},
				        {"appointments", Int64.Type}
				    })
				in
				    Typed
