table wl_head

	column waiting
		dataType: int64
		summarizeBy: sum
		sourceColumn: waiting

	column past_requested
		dataType: int64
		summarizeBy: sum
		sourceColumn: past_requested

	column avg_waiting
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_waiting

	column high_priority
		dataType: int64
		summarizeBy: sum
		sourceColumn: high_priority

	measure 'Waitlist past requested-by' = SELECTEDVALUE ( 'wl_head'[past_requested] )
		formatString: #,0
		displayFolder: Measures
		/// 53.0% of the waitlist

	partition wl_head = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\wl_head.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"waiting", Int64.Type},
				        {"past_requested", Int64.Type},
				        {"avg_waiting", type number},
				        {"high_priority", Int64.Type}
				    })
				in
				    Typed
